INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);
INSERT INTO contact (contact_id) VALUES (default);

INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (1, '2009-06-04 18:13:56', 'deposit', 1);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (2, '2018-01-01 00:00:00', 'account', 1);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (3, '2018-01-01 18:13:56', 'deposit', 1);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (4, '2009-02-04 00:00:00', 'account', 2);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (5, '2009-06-04 18:13:56', 'deposit', 2);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (6, '2009-06-04 18:13:56', 'account', 3);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (7, '2009-06-04 18:13:56', 'deposit', 4);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (8, '2009-06-04 18:13:56', 'account', 4);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (9, '2009-06-04 18:13:56', 'deposit', 4);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (10, '2007-06-04 18:13:56', 'account', 10);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (11, '2008-06-04 18:13:56', 'deposit', 10);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (12, '2009-06-04 18:13:56', 'account', 10);
INSERT  INTO application (application_id, dt_created, product_name, contact_id) values (13, '2010-06-04 18:13:56', 'deposit', 10);
